apiVersion: apps/v1
kind: Deployment
metadata:
  name: hexgl
  labels:
    module: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hexgl
  template:
    metadata:
      labels:
        app: hexgl
    spec:
      containers:
      - name: pvpn
        image: jaxa/hexgl:arm64
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: hexgl
spec:
  type: NodePort
  selector:
    app: hexgl
  ports:
  - name: "32608"
    port: 32608
    targetPort: 8000
    nodePort: 32608
